### ISSUE TITLE
[Remove Request] - k.sni.global.fastly.net from adobe.txt

### ISSUE THREAD

**Issue by Rno-1** [blocklistproject/Lists#1049]
URL you wish to be removed:
k.sni.global.fastly.net

Why you believe this to be a false positive:
verywellfit.com relies on k.sni.global.fastly.net for loading, or else it'll bring up a "site can’t be reached" error.
verywellfit is a legit site, but to be fair, I'm not sure if this is a valid reason or not to report it as a false positive.

List it is on:
adobe.txt

Other info you think we should know:
In pi-hole's web portal, it says
www.verywellfit.com
(blocked k.sni.global.fastly.net)

**Comment by gap579137** [comment]
fixed and closed with push

**Comment by eur0pa** [comment]
Not closed / fixed. `k.sni.global.fastly.net` is still present in `adobe.txt`. Still prevents seriouseats.com from loading.
